[package]
name = "fractal-dto"
<<<<<<< HEAD
version = "0.0.8"
=======
version = "0.0.9"
>>>>>>> release/0.0.9
authors = [
    "Eric Remigino <eric@fractal.global>",
    "Iban Eguia <iban@fractal.global>",
]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/FractalGlobal/dto-rs"
documentation = "http://fractal.global/dto-rs"
description = """
DTO objects to transfer information in the Fractal Global Credits API.
"""
keywords = ["fractal", "global", "credits", "dto"]

[dependencies]
rustc-serialize = "^0.3"
chrono = { version = "^0.2", features = ["rustc-serialize"]}
fractal-utils = "^0.1"
